sudo: required

services:
  - docker # Install docker in Travis

before_install:
  - docker build -t programmingwithbadri/frontend -f Dockerfile.dev . # Builds the docker image

script:
  - docker run -e CI=true programmingwithbadri/frontend npm run test # Runs the test and exit from image