version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "192.168.99.100:3000:3000"
    volumes:
      - /home/app/node_modules
      - .:/home/app/
